-- *******************************************
--  Creación de Tabla HORARIO 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HORARIO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.HORARIO (
    ID_HORARIO          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_DISPONIBILIDAD   NUMBER          NOT NULL
                        CONSTRAINT FK_HORARIO_DISPONIBILIDAD REFERENCES DISPONIBILIDAD (ID_DISPONIBILIDAD) ON DELETE CASCADE,
    FECHA               DATE,    
    CUPO_MAXIMO         NUMBER,
                        
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;