-- *******************************************
--  Creación de Tabla ESTADO_CITA 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ESTADO_CITA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.ESTADO_CITA (
    ID_ESTADO           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    NOMBRE              VARCHAR2(15)    NOT NULL
                        CONSTRAINT UQ_ESTADO_CITA_NOMBRE UNIQUE,
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;