-- *******************************************
--  Creación de Tabla ESPECIALIDAD 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.ESPECIALIDAD (
    ID_ESPECIALIDAD     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    NOMBRE              VARCHAR2(20)   NOT NULL
                        CONSTRAINT UQ_ESPECIALIDAD_NOMBRE UNIQUE,
    DESCRIPCION         NVARCHAR2(60)  DEFAULT NULL,
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;