-- *******************************************
--  Creación de Tabla CITA 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CITA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.CITA (
    ID_CITA         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    ID_PACIENTE     NUMBER          NOT NULL
                        CONSTRAINT FK_CITA_PACIENTE REFERENCES PACIENTE (ID_PACIENTE) ON DELETE CASCADE,
    ID_MEDICO       NUMBER          NOT NULL
                        CONSTRAINT FK_CITA_MEDICO REFERENCES MEDICO (ID_MEDICO) ON DELETE CASCADE,
    ID_ESTADO       NUMBER          NOT NULL
                        CONSTRAINT FK_CITA_ESTADO REFERENCES ESTADO_CITA (ID_ESTADO) ON DELETE CASCADE,
    FECHA           DATE            NOT NULL,
    HORA            TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    DIAGNOSTICO     VARCHAR2(120)   DEFAULT NULL,
    OBSERVACIONES   VARCHAR2(120)   DEFAULT NULL,
    
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;