-- *******************************************
--  Creación de Tabla SEDE 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SEDE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.SEDE (
    ID_SEDE             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    NOMBRE              VARCHAR2(50)    NOT NULL,
    DIRECCION           VARCHAR2(50)    NOT NULL,
    TELEFONO            NUMBER(9),
    ID_DISTRITO         NUMBER
                        CONSTRAINT FK_SEDE_DISTRITO REFERENCES DISTRITO (ID_DISTRITO) ON DELETE CASCADE,
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;