-- *******************************************
--  Creación de Tabla ALERGIA 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ALERGIA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.ALERGIA (
    ID_ALERGIA          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    NOMBRE              NVARCHAR2(25)   NOT NULL
                        CONSTRAINT      UQ_ALERGIA_NOMBRE UNIQUE,
    DESCRIPCION         NVARCHAR2(40)   DEFAULT NULL,
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;