-- *******************************************
--  Creación de Tabla GRUPO_SANGUINEO 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GRUPO_SANGUINEO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.GRUPO_SANGUINEO (
    ID_GRUPO_SANGUINEO  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    NOMBRE              VARCHAR2(20)    NOT NULL
                        CONSTRAINT UQ_GRUPO_SANGUINEO_NOMBRE UNIQUE,
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;