-- *******************************************
--  Creación de Tabla DISTRITO 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DISTRITO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.DISTRITO (
    ID_DISTRITO         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    NOMBRE              VARCHAR2(20) NOT NULL,
    ID_PROVINCIA        NUMBER
                        CONSTRAINT FK_DISTRITO_PROVINCIA REFERENCES PROVINCIA (ID_PROVINCIA) ON DELETE CASCADE,
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;