-- *******************************************
--  Creación de Tabla DISPONIBILIDAD 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DISPONIBILIDAD CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.DISPONIBILIDAD (
    ID_DISPONIBILIDAD   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_MEDICO           NUMBER          NOT NULL
                        CONSTRAINT FK_DISPONIBILIDAD_MEDICO REFERENCES MEDICO (ID_MEDICO) ON DELETE CASCADE,
    DIA_SEMANA          NUMBER          DEFAULT 1,
    
    HORA_INICIO         TIMESTAMP,
    HORA_FIN            TIMESTAMP,
                        
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;