-- *******************************************
--  Creación de Tabla PACIENTE_ALERGIA 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PACIENTE_ALERGIA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.PACIENTE_ALERGIA (
    ID_PACIENTE     NUMBER          NOT NULL
                        CONSTRAINT FK_PACIENTE_ALERGIA_PACIENTE REFERENCES PACIENTE (ID_PACIENTE) ON DELETE CASCADE,
    ID_ALERGIA         NUMBER          NOT NULL
                        CONSTRAINT FK_PACIENTE_ALERGIA_ALERGIA REFERENCES ALERGIA (ID_ALERGIA) ON DELETE CASCADE,    
    
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    
    CONSTRAINT pk_paciente_alergia PRIMARY KEY (ID_PACIENTE, ID_ALERGIA)
);

COMMIT;