-- *******************************************
--  Creación de Tabla MEDICO 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MEDICO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.MEDICO (
    ID_MEDICO         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    NOMBRES             VARCHAR2(60),
    APELLIDO_PATERNO    VARCHAR2(20),
    APELLIDO_MATERNO    VARCHAR2(20),
    COLEGIATURA         NUMBER          NOT NULL
                        CONSTRAINT UQ_MEDICO_COLEGIATURA UNIQUE,
    TELEFONO            NUMBER(9),
    CORREO              VARCHAR2(50)
                        CONSTRAINT UQ_MEDICO_CORREO UNIQUE,
    ID_ESPECIALIDAD     NUMBER          NOT NULL
                        CONSTRAINT FK_MEDICO_ESPECIALIDAD REFERENCES ESPECIALIDAD (ID_ESPECIALIDAD) ON DELETE CASCADE,
    ID_SEDE         NUMBER          NOT NULL
                        CONSTRAINT FK_MEDICO_SEDE REFERENCES SEDE (ID_SEDE) ON DELETE CASCADE,
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE MEDICITA_DB_USR.MEDICO
ADD CONSTRAINT CHK_MEDICO_CORREO_VALIDO CHECK (
    REGEXP_LIKE(CORREO, '^.+@.+\..+$')
    OR CORREO IS NULL -- Permite valores NULL si la columna no es NOT NULL
);
COMMIT;