-- *******************************************
--  Creación de Tabla PROVINCIA 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PROVINCIA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.PROVINCIA (
    ID_PROVINCIA        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    NOMBRE              VARCHAR2(40)    NOT NULL,
    ID_DEPARTAMENTO     NUMBER          NOT NULL
                        CONSTRAINT FK_PROVINCIA_DEPARTAMENTO REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO) ON DELETE CASCADE,
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;