ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE MEDICITA_DB 
DATAFILE 'medicita_db_01.dbf' 
SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE 200M;

CREATE USER MEDICITA_DB_USR IDENTIFIED BY Medicita
DEFAULT TABLESPACE MEDICITA_DB
QUOTA UNLIMITED ON MEDICITA_DB;

GRANT CONNECT, RESOURCE, CREATE VIEW TO MEDICITA_DB_USR;