-- *******************************************
--  Creación de Tabla HISTORIAL 
-- *******************************************
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HISTORIAL CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            NULL;
        END IF;
END;
/

CREATE TABLE MEDICITA_DB_USR.HISTORIAL (
    ID_HISTORIAL        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    ID_CITA     NUMBER          NOT NULL
                        CONSTRAINT FK_HISTORIAL_CITA REFERENCES CITA (ID_CITA) ON DELETE CASCADE,
    DIAGNOSTICO         VARCHAR2(120)   DEFAULT NULL,
    OBSERVACIONES       VARCHAR2(120)   DEFAULT NULL,
    REG_CREACION        TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL,
    REG_MODIFICACION    TIMESTAMP(2)    DEFAULT SYSTIMESTAMP NOT NULL
);

COMMIT;